#!/bin/bash
"exec" "jython" "$0" "$@"

from java.awt import MouseInfo, Robot
from java.lang import Thread
from argparse import ArgumentParser, RawTextHelpFormatter
from time import time
from datetime import timedelta
from sys import exit
from sys.stdout import write, flush
from signal import signal, SIGINT


initial_time = time()
duration = None
silent = False


def main():
    global initial_time, duration, silent
    signal(SIGINT, ctrlc)
    parser = ArgumentParser(
        prog='awake',
        description='Keeps your computer awake using tiny mouse movements' +
        '\nRuns indefinitely by default but may be provided a specific' +
        ' amount of time to lapse',
        conflict_handler='resolve',
        formatter_class=RawTextHelpFormatter)
    parser.add_argument('--hours', '-H', type=int, default=0,
                        help='number of hours')
    parser.add_argument('--minutes', '-M', type=int, default=0,
                        help='number of minutes')
    parser.add_argument('--seconds', '-S', type=int, default=0,
                        help='number of seconds')
    parser.add_argument('--silent', '-s', action='store_true')
    args = parser.parse_args()
    silent = args.silent
    if (args.hours == 0 and args.minutes == 0 and args.seconds == 0):
        duration = 0
        log('Running indefinitely')
    else:
        duration = int(args.hours * 60 * 60 + args.minutes * 60 + args.seconds)
        log('Running for: {:0>8}'
            .format(timedelta(seconds=duration)))

    robot = Robot()
    info = MouseInfo.getPointerInfo()
    last_time = time()
    update_time(last_time)
    last_location = info.getLocation()
    robot.setAutoWaitForIdle(True)

    while(True):
	current_time = time()
        update_time(current_time)
        if (duration != 0 and time() >= duration + initial_time):
            ctrlc()

	if current_time >= (last_time + 10):
            info = MouseInfo.getPointerInfo()
            current_location = info.getLocation()
            if(last_location.equals(current_location)):
                x = int(current_location.getX())
                y = int(current_location.getY())
                robot.mouseMove(x + 1, y + 1)
                robot.mouseMove(x, y)
            last_location = current_location
	    last_time = current_time

        Thread.sleep(500)


def update_time(t):
    if not silent:
        write(
            '\rAwake for: {:0>8}'
            .format(timedelta(seconds=int(t - initial_time))))
        flush()


def ctrlc(signal=None, frame=None):
    update_time(time())
    log('')
    exit(0)


def log(s):
    if not silent:
        print(s)


if __name__ == "__main__":
    main()

# vim: set ft=python:
